"""Attach-time normalization helpers for FabricHandshakeRecorder."""

from __future__ import annotations

from typing import Any, Dict, Sequence

from detm.runtime.fabric import normalize_fabric_handshake_recorder_attach_kwargs


def build_attach_kwargs(
    *,
    node_id: str,
    commit_channel: str,
    ack_channel: str,
    mode_filter: str | None,
    split_mode_channels: bool,
    required_proof_accepts: int,
    required_trust_accepts: int,
    required_unique_proof_validators: int,
    required_unique_trust_validators: int,
    required_validator_ids: Sequence[str] | None,
    handshake_profile: str,
    enforce_required_validator_ids: bool,
    enforce_active_validator_membership: bool,
    enforce_ack_sender_validator_match: bool,
    enforce_ack_auth_key_id_binding: bool,
    validator_auth_key_ids: Dict[str, Sequence[str] | str] | Sequence[str] | str | None,
    enforce_ack_transport_identity_binding: bool,
    validator_transport_identities: Dict[str, Sequence[str] | str] | Sequence[str] | str | None,
    reject_on_any_reject: bool,
    publish_retry_attempts: int,
    commit_publish_retry_attempts: int,
    delivery_required_receipts: int,
    delivery_guarantee_mode: str,
    delivery_required_validator_ids: Sequence[str] | None,
    delivery_enforce_required_validator_ids: bool,
    delivery_reject_on_any_reject: bool,
    delivery_retry_interval_ms: int,
    delivery_max_attempts: int,
    delivery_timeout_ms: int,
    delivery_tracking_state_path: str | None,
    delivery_ack_channel: str,
    delivery_emit_ack: bool,
    pending_timeout_ms: int | None,
    transport: str,
    transport_host: str,
    transport_port: int,
    transport_connect: bool,
    transport_keep_open: bool,
    transport_backpressure_max_pending: int | None,
    transport_backpressure_policy: str,
    transport_backpressure_block_timeout_ms: int,
    transport_dedup_ingress_enabled: bool,
    transport_dedup_ttl_ms: int,
    transport_dedup_max_entries: int,
    transport_auth_enabled: bool,
    transport_auth_key: str | None,
    transport_auth_key_id: str | None,
    transport_tls_enabled: bool,
    transport_tls_server_hostname: str | None,
    transport_tls_ca_file: str | None,
    transport_tls_cert_file: str | None,
    transport_tls_key_file: str | None,
    transport_tls_require_client_cert: bool,
    transport_tls_client_ca_file: str | None,
    transport_tls_insecure_skip_verify: bool,
    transport_tls_identity_source: str,
    transport_tls_identity_fallback_to_fingerprint: bool,
    artifact_store_dir: str | None,
    publish_inline_payload: bool,
    replay_sample_stride: int,
    replay_policy_tier: str,
    replay_strict_window_size: int,
    validator_coordination_state_path: str | None,
    validator_coordination_replica_paths: Sequence[str] | None,
    validator_coordination_replica_read_quorum: int | None,
    validator_coordination_replica_write_quorum: int | None,
    epoch_state_path: str | None,
    epoch_replica_state_paths: Sequence[str] | None,
    epoch_replica_read_quorum: int | None,
    epoch_replica_write_quorum: int | None,
    epoch_lock_timeout_ms: int,
    epoch_lock_poll_ms: int,
    epoch_lock_stale_ms: int | None,
    epoch_consensus_required_total_accepts: int,
    epoch_consensus_timeout_ms: int,
    epoch_consensus_max_attempts: int,
    epoch_consensus_reject_on_any_reject: bool,
    epoch_consensus_channel: str,
    epoch_consensus_enabled: bool,
    delivery_outbox_path: str | None,
    delivery_outbox_replica_paths: Sequence[str] | None,
    delivery_outbox_replica_read_quorum: int | None,
    delivery_outbox_replica_write_quorum: int | None,
    delivery_outbox_max_entries: int | None,
    delivery_outbox_flush_limit: int | None,
    delivery_outbox_drop_policy: str,
    fabric_acks_retention_window: int,
    fabric_acks_compaction_budget: int,
    fabric_ack_envelopes_retention_window: int,
    fabric_ack_envelopes_compaction_budget: int,
    fabric_delivery_acks_retention_window: int,
    fabric_delivery_acks_compaction_budget: int,
    fabric_dead_letters_retention_window: int,
    fabric_dead_letters_compaction_budget: int,
    fabric_quorum_report_retention_window: int,
    fabric_quorum_report_compaction_budget: int,
) -> dict[str, Any]:
    return normalize_fabric_handshake_recorder_attach_kwargs(
        node_id=node_id,
        commit_channel=commit_channel,
        ack_channel=ack_channel,
        mode_filter=mode_filter,
        split_mode_channels=split_mode_channels,
        required_proof_accepts=required_proof_accepts,
        required_trust_accepts=required_trust_accepts,
        required_unique_proof_validators=required_unique_proof_validators,
        required_unique_trust_validators=required_unique_trust_validators,
        required_validator_ids=required_validator_ids,
        handshake_profile=handshake_profile,
        enforce_required_validator_ids=enforce_required_validator_ids,
        enforce_active_validator_membership=enforce_active_validator_membership,
        enforce_ack_sender_validator_match=enforce_ack_sender_validator_match,
        enforce_ack_auth_key_id_binding=enforce_ack_auth_key_id_binding,
        validator_auth_key_ids=validator_auth_key_ids,
        enforce_ack_transport_identity_binding=enforce_ack_transport_identity_binding,
        validator_transport_identities=validator_transport_identities,
        reject_on_any_reject=reject_on_any_reject,
        publish_retry_attempts=publish_retry_attempts,
        commit_publish_retry_attempts=commit_publish_retry_attempts,
        delivery_required_receipts=delivery_required_receipts,
        delivery_guarantee_mode=delivery_guarantee_mode,
        delivery_required_validator_ids=delivery_required_validator_ids,
        delivery_enforce_required_validator_ids=delivery_enforce_required_validator_ids,
        delivery_reject_on_any_reject=delivery_reject_on_any_reject,
        delivery_retry_interval_ms=delivery_retry_interval_ms,
        delivery_max_attempts=delivery_max_attempts,
        delivery_timeout_ms=delivery_timeout_ms,
        delivery_tracking_state_path=delivery_tracking_state_path,
        delivery_ack_channel=delivery_ack_channel,
        delivery_emit_ack=delivery_emit_ack,
        pending_timeout_ms=pending_timeout_ms,
        transport=transport,
        transport_host=transport_host,
        transport_port=transport_port,
        transport_connect=transport_connect,
        transport_keep_open=transport_keep_open,
        transport_backpressure_max_pending=transport_backpressure_max_pending,
        transport_backpressure_policy=transport_backpressure_policy,
        transport_backpressure_block_timeout_ms=transport_backpressure_block_timeout_ms,
        transport_dedup_ingress_enabled=transport_dedup_ingress_enabled,
        transport_dedup_ttl_ms=transport_dedup_ttl_ms,
        transport_dedup_max_entries=transport_dedup_max_entries,
        transport_auth_enabled=transport_auth_enabled,
        transport_auth_key=transport_auth_key,
        transport_auth_key_id=transport_auth_key_id,
        transport_tls_enabled=transport_tls_enabled,
        transport_tls_server_hostname=transport_tls_server_hostname,
        transport_tls_ca_file=transport_tls_ca_file,
        transport_tls_cert_file=transport_tls_cert_file,
        transport_tls_key_file=transport_tls_key_file,
        transport_tls_require_client_cert=transport_tls_require_client_cert,
        transport_tls_client_ca_file=transport_tls_client_ca_file,
        transport_tls_insecure_skip_verify=transport_tls_insecure_skip_verify,
        transport_tls_identity_source=transport_tls_identity_source,
        transport_tls_identity_fallback_to_fingerprint=transport_tls_identity_fallback_to_fingerprint,
        artifact_store_dir=artifact_store_dir,
        publish_inline_payload=publish_inline_payload,
        replay_sample_stride=replay_sample_stride,
        replay_policy_tier=replay_policy_tier,
        replay_strict_window_size=replay_strict_window_size,
        validator_coordination_state_path=validator_coordination_state_path,
        validator_coordination_replica_paths=validator_coordination_replica_paths,
        validator_coordination_replica_read_quorum=validator_coordination_replica_read_quorum,
        validator_coordination_replica_write_quorum=validator_coordination_replica_write_quorum,
        epoch_state_path=epoch_state_path,
        epoch_replica_state_paths=epoch_replica_state_paths,
        epoch_replica_read_quorum=epoch_replica_read_quorum,
        epoch_replica_write_quorum=epoch_replica_write_quorum,
        epoch_lock_timeout_ms=epoch_lock_timeout_ms,
        epoch_lock_poll_ms=epoch_lock_poll_ms,
        epoch_lock_stale_ms=epoch_lock_stale_ms,
        epoch_consensus_required_total_accepts=epoch_consensus_required_total_accepts,
        epoch_consensus_timeout_ms=epoch_consensus_timeout_ms,
        epoch_consensus_max_attempts=epoch_consensus_max_attempts,
        epoch_consensus_reject_on_any_reject=epoch_consensus_reject_on_any_reject,
        epoch_consensus_channel=epoch_consensus_channel,
        epoch_consensus_enabled=epoch_consensus_enabled,
        delivery_outbox_path=delivery_outbox_path,
        delivery_outbox_replica_paths=delivery_outbox_replica_paths,
        delivery_outbox_replica_read_quorum=delivery_outbox_replica_read_quorum,
        delivery_outbox_replica_write_quorum=delivery_outbox_replica_write_quorum,
        delivery_outbox_max_entries=delivery_outbox_max_entries,
        delivery_outbox_flush_limit=delivery_outbox_flush_limit,
        delivery_outbox_drop_policy=delivery_outbox_drop_policy,
        fabric_acks_retention_window=fabric_acks_retention_window,
        fabric_acks_compaction_budget=fabric_acks_compaction_budget,
        fabric_ack_envelopes_retention_window=fabric_ack_envelopes_retention_window,
        fabric_ack_envelopes_compaction_budget=fabric_ack_envelopes_compaction_budget,
        fabric_delivery_acks_retention_window=fabric_delivery_acks_retention_window,
        fabric_delivery_acks_compaction_budget=fabric_delivery_acks_compaction_budget,
        fabric_dead_letters_retention_window=fabric_dead_letters_retention_window,
        fabric_dead_letters_compaction_budget=fabric_dead_letters_compaction_budget,
        fabric_quorum_report_retention_window=fabric_quorum_report_retention_window,
        fabric_quorum_report_compaction_budget=fabric_quorum_report_compaction_budget,
    )


__all__ = ["build_attach_kwargs"]
